# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4202d7d8f1a41b1f7517f91e37cffcc7afff0109b14553eaced75eee7d8ff35d824583673b337b3902ce9ffb3b4953a2b3b98a8b9cfe180fe48f29e94c1e5e12
  
  action_mailer:
    default_url_options:
      host: "localhost:3000"
    delivery_method: "smtp"

    smtp_settings:
      address: "smtp.gmail.com"
      domain: "gmail.com"
      port: "587"
      user_name: "bullet81"
      password: "wypierdalaj"
      authentication: :plain
      enable_starttls_auto: "true"

test:
  secret_key_base: 1d42cb1497c5c93f7138ab7132a46b68f97d768e7824456b1570e1e89cd1c1cf656c12f914c9c08fe4e7f6e5ccd3e8f316a0dd632360f9b58827c51494214758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
